name: 7onez

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/bluetank2772/gputurbo/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://i.imgur.com/vuXVHI4.png -OutFile wallpaper.png
        Invoke-WebRequest https://raw.githubusercontent.com/bluetank2772/gputurbo/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/bluetank2772/gputurbo/main/loop.bat -OutFile loop.bat
    - name: Download Launcher.
      run: |
        Invoke-WebRequest https://github.com/bluetank2772/gputurbo/raw/main/AutoTangLikeCheo.zip -OutFile AutoTangLikeCheo.zip
    - name: Extract Ngrok File.
      run: Expand-Archive ngrok.zip
    - name: Connect to Ngrok.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enabling access to RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.png D:\a\wallpaper.png
        copy wallpaper.bat C:\Users\Public\Desktop\wallpaper.bat
        copy AutoTangLikeCheo.zip C:\Users\Public\Desktop\AutoTangLikeCheo.zip
    - name: Open Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Thông tin RPD miễn phí của bạn CPU 2 Core - 7GB Ram - 256 SSD.
      run: cmd /c start.bat
    - name: Made Successfully! You Can Close Tab Now.
      run: cmd /c loop.bat
