name: 7onez

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/tricker7272/bluered/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://i.imgur.com/vuXVHI4.png -OutFile wallpaper.png
        Invoke-WebRequest https://raw.githubusercontent.com/tricker7272/bluered/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/tricker7272/bluered/main/loop.bat -OutFile loop.bat
    - name: Download Launcher.
      run: |
        
    - name: Extract Ngrok File.
      run: Expand-Archive ngrok.zip
    - name: Connect to Ngrok.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN2
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN2 }}
    - name: Enabling access to RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.png D:\a\wallpaper.png
        copy wallpaper.bat C:\Users\Public\Desktop\wallpaper.bat
    - name: Open Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Thông tin RPD miễn phí của bạn CPU 2 Core - 7GB Ram - 256 SSD.
      run: cmd /c start.bat
    - name: All Done! You can close Tab now! Maximum VM time:6h.
      run: cmd /c loop.bat
